### PR TITLE
Support for multiple KNX Interfaces.

### PR DESCRIPTION
**Pull request by encbladexp**
This pull request enables support for multiple KNX interfaces per smarthome instance. The existing behavior is not changed.

Missing things:
- Documentation
- Item Inheritance (use same KNX Interface on a tree of KNX items)

### CODE REVIEW

**Comment by encbladexp** [comment]
Rebased on current develop...

**Comment by encbladexp** [comment]
Rebased another Time. Is there any chance of getting this PR applied?

**Comment by cstrassburg** [comment]
added to [https://github.com/smarthomeNG/smarthome](https://github.com/smarthomeNG/smarthome)

**Comment by ohinckel** [comment]
@cstrassburg I just created a new PR https://github.com/smarthomeNG/smarthome/pull/50 which means, that this PR can be changed in that way that is will use the plugin methods introduced by the https://github.com/smarthomeNG/smarthome/pull/50.

Do you merged the stuff to smarthomeNG already?

**Pull request closed without merging**
