### PR TITLE
PlugIn: Onewire LinkLocater for iButtons

### PR DESCRIPTION
**Pull request by KHome**
Is there a feature to distinguish between different Onewire iButton readers with LinkLocators.

Scenario:
2 Doors with 1 Onewire Bus, but on each door a LinkLocator "locator"
Have another actions depending on doors (location).

BR,
KHome

### CODE REVIEW

**Comment by ohinckel** [comment]
Do you want to just open an issue and ask your question, or did you develop something and want to merge it into develop branch?

You request seems to be not started on the current develop branch and contains a lot of changes. I think this was not intended by you. Was it?

**Comment by KHome** [comment]
Do you want to just open an issue 
> Yes
and ask your question,
> Yes, does this already exstis?
 or did you develop something and want to merge it into develop branch?
> Not yet. But I think I could, if I would receive some hints.

You request seems to be not started 
> Correct, not started yet
on the current develop branch and contains a lot of changes.
> I don't really understand. I'm new to GITHUB. Do you mean that this request will result in lot of changes?

 I think this was not intended by you. Was it?
> First of all, I just wanted to get the status, if this is already planned / requested.
> If this is not the case, I would like to create this feature.

Best regards,
KHome

**Comment by ohinckel** [comment]
The best way to ask questions is to just open a [new issue](https://github.com/mknx/smarthome/issues/new) and do not start with a pull request.

If you want to develop some changes later, you can start with it by using an up-to-date develop branch and create a new branch from it to implement your changes in. After you finished, create a new pull request with your new branch.

I suggest that you create a new issue and Marcus should close this.

**Comment by KHome** [comment]
Ok,  I will open an issue

**Pull request closed without merging**
