### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AndreyHeaven**

### CODE REVIEW

**Comment by rthill** [comment]
Why did you immediately close this pull request? Do you still plan to work on YAML parser for sh.py?

**Comment by ohinckel** [comment]
I think it should not completely remove support for the old `conf` format since it break backward compatibility. Instead it should add support for new formats. E.g. it could be determined by looking at the configuration file's extension (`.conf` for the current implementation, `.yml` for the implementation in this pull request, `.xml` for configuration in XML - if really one need this).

Btw. weeks days ago I also started to rewrite the configuration reading by my own to support other configuration formats and sources (e.g. reading configuration from a database - but this depends on #69). If somebody else is interested in supporting different format and sources, I would try to integrate this pull request into a new one which includes my modifications. This implementation is also open for adding support for new formats (like XML, JSON, ...).

**Comment by rthill** [comment]
That sounds great. I think it makes it easy for everyone to create new readers as soon as you include your modifications to support different readers by looking at the file extension.

**Comment by AndreyHeaven** [comment]
i glad to hear that my work is interested for guys. but i cant prepare pure pull request. but i can give code to someone who can. it is very interesting to have different parsers

**Comment by ohinckel** [comment]
I could try to use the [patch](https://github.com/mknx/smarthome/pull/203.patch) and integrate this into a new branch, containing also my changes to support different formats. Since it is also touching SmartHome's core, I could not say if it will get merged or not. @mknx needs to decide.

**Comment by AndreyHeaven** [comment]
@ohinckel  i think patch of this pull request is not all that you need. may be i coded something more

**Comment by ohinckel** [comment]
OK, in this case use `git diff <from-hash>..<to-hash>` to generate a patch file for your commits. Alternatively you can also use `git format-patch <from-hash>..<to-hash>` to create a patch file for each commit. After this you could create a gist.

But it would be easier if you could provide all of your changes in a separate branch.

**Pull request closed without merging**
